proxy:
  listen_address: "0.0.0.0:2022"
  log_dir: "./logs"
  host_key: "keys/proxy_host_keys/proxy_host_key"
  allowed_users:
    - username: "user1"
      public_key_path: "./keys/client_keys/pub/user1_rsa.pub"
      password: "pass1"
    - username: "user2"
      public_key_path: "./keys/client_keys/pub/user2_rsa.pub"
      password: "pass2"

upstream:
  host: "openssh-server"
  port: 2222
  username: "proxyserver"
  upstream_host_key_path: "./keys/upstream_auth/.ssh/known_hosts/ssh_host_ecdsa_key.pub"
  client_private_key_path: "./keys/upstream_auth/.ssh/client_priv/id_rsa"
  password: ""

llm:
  api_key: ""
  prompt: "Here is a log of the stdin from a userâ€™s SSH session with an upstream host (user is interacting with a proxy, proxy communicates user input upstream). Please analyze the session and provide a concise summary of the user's actions. Additionally, assess any potential security risks based on the commands entered -- remember to be concise, and to use the discretion of a cybersecurity expert. Not every shell session will have a security risk, but be aware of vulnerabilities."